version: 2

defaults: &defaults
  machine:
    enabled: true

defaults-docker: &defaults-docker
  docker:
    - image: circleci/buildpack-deps:bionic

build-dep: &build-dep
  name: Install build dependencies
  command: sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3

ssl-event-boost-dep: &ssl-event-boost-dep
  name: Install ssl, event and boost dependency
  command: sudo apt install libssl-dev libevent-dev libboost-all-dev

zlib-seccomp-cap-dep: &zlib-seccomp-cap-dep
  name: Install zlib, libseccomp and libcap
  command: sudo apt-get install zlib1g-dev libseccomp-dev libcap-dev libncap-dev

run_apt_packages: &run_apt_packages
  name: Prepare VM
  command: sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common git python3

set_python_version: &set_python_version
  name: Set Python Version
  command: pyenv global 3.5.2

run_base_setup: &run_base_setup
  name: Setup repo and execute VM builder
  command: ./gitian-build.py --docker --commit --setup marpme master

semvers: &semvers /v(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/

jobs:
  release-prepare-machine:
    <<: *defaults
    steps:
      - run:
          <<: *run_apt_packages
      - checkout:
          path: ~/project/verge
      - run:
          name: Hardcopy gitian build script
          command: cp ./verge/contrib/gitian-build.py . && chmod u+x gitian-build.py
      - run:
          name: Prepare VM Builder
          command: git clone https://github.com/newroco/vmbuilder.git && cd vmbuilder && sudo chmod u+x setup.py && sudo ./setup.py install
      - persist_to_workspace:
          root: '.'
          paths:
            - '.'

  release-windows:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          <<: *run_apt_packages
      - run:
          <<: *set_python_version
      - run:
          <<: *run_base_setup
      - run:
          name: Gitian Build Windows
          command: ./gitian-build.py --docker --detach-sign -o w --commit -j 4 -m 4000 -b marpme master
      - persist_to_workspace:
          root: .
          paths: 'verge-binaries/master'

  release-macos:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          <<: *run_apt_packages
      - run:
          <<: *set_python_version
      - run:
          <<: *run_base_setup
      - run:
          name: Add OSX SDK
          command: mkdir -p gitian-builder && cd ./gitian-builder && mkdir -p inputs && cd inputs && curl -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.11.sdk.tar.xz --output MacOSX10.11.sdk.tar.gz
      - run:
          name: Gitian Build MacOS
          command: ./gitian-build.py --docker --detach-sign -o m --commit -j 4 -m 4000 -b marpme master
      - persist_to_workspace:
          root: .
          paths: 'verge-binaries/master'

  release-linux:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          <<: *run_apt_packages
      - run:
          <<: *set_python_version
      - run:
          <<: *run_base_setup
      - run:
          name: Gitian Build Linux
          command: ./gitian-build.py --docker --detach-sign -o l --commit -j 4 -m 4000 -b marpme master
      - persist_to_workspace:
          root: .
          paths: 'verge-binaries/master'

  upload-github-releases:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: ./verge-binaries/master
      - run:
          name: 'Publish Release on GitHub'
          command: |
            VERSION=$(git describe)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -delete ${CIRCLE_TAG} ./verge-binaries/master/verge-binaries/master/

  build-verge-core:
    <<: *defaults-docker
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 && sudo apt install libssl-dev libevent-dev libboost-all-dev && sudo apt-get install zlib1g-dev libseccomp-dev libcap-dev libncap-dev && sudo apt-get install software-properties-common && sudo add-apt-repository ppa:bitcoin/bitcoin -y && sudo apt-get update && sudo apt-get install libdb4.8-dev libdb4.8++-dev && sudo apt-get install libminiupnpc-dev && sudo apt-get install libzmq3-dev && sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler && sudo apt-get install libqrencode-dev
      - run:
          name: Autogen tools
          command: ./autogen.sh
      - run:
          name: Configuring code
          command: ./configure --disable-bench --without-gui --disable-dependency-tracking --disable-werror
      - run:
          name: Make
          command: make -j4
      - run: 
          name: Install pip
          command: sudo apt install python3-pip
      - run: 
          name: Install scrypt for python
          command: pip3 install --user scrypt
      - run:
          name: Run regression checks
          command: ./test/functional/test_runner.py --combinedlogslen=4000 --failfast
      - persist_to_workspace:
          root: '.'
          paths:
            - '.'

  run-unit-tests:
    <<: *defaults-docker
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: Check binaries
          command: make check

  run-util-tests:
    <<: *defaults-docker
    steps:
      - attach_workspace:
          at: '.'
      - run:
          name: Run RPC Auth test
          command: ./test/util/rpcauth-test.py
      - run: 
          name: Run config checks
          command: ./test/util/verge-util-test.py

  run-lint-tests:
    docker:
      - image: circleci/python:3.7.3
    steps: 
      - attach_workspace:
          at: '.'
      - run:
          name: Install dependencies
          command: pip install --user flake8 && sudo apt-get install shellcheck
      - run:
          name: Run linting checks
          command: ./test/lint/lint-all.sh

  run-regression-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: '.'
      - run: 
          name: Install pip
          command: sudo apt install python3-pip
      - run: 
          name: Install scrypt for python
          command: pip install --user scrypt
      - run: 
          <<: *build-dep
      - run: 
          <<: *ssl-event-boost-dep
      - run: 
          <<: *zlib-seccomp-cap-dep
      # - run:
      #     name: Run regression checks
      #     command: ./test/functional/test_runner.py --combinedlogslen=4000 --failfast

workflows:
  version: 2
  release:
    jobs:
      - release-prepare-machine:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - release-windows:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - release-prepare-machine
      - release-macos:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - release-prepare-machine
      - release-linux:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - release-prepare-machine
      - upload-github-releases:
          context: github-gangster
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - release-windows
            - release-macos
            - release-linux

  testing:
    jobs:
      - build-verge-core
      - run-unit-tests:
          requires:
            - build-verge-core
      - run-util-tests:
          requires:
            - build-verge-core
      - run-regression-tests:
          requires:
            - build-verge-core
